## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.0.38:3306/notes_app?useSSL=false
#    username: root
#    password: 1234
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notes_app

server:
  port: 9000